# Generated by Django 2.2.5 on 2020-04-01 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Advisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgpa', models.PositiveIntegerField()),
                ('active_backs', models.PositiveIntegerField()),
                ('passive_backs', models.PositiveIntegerField()),
                ('sem', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advisor.students')),
            ],
        ),
    ]
