# Generated by Django 3.0.3 on 2020-03-20 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Advisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=4)),
                ('batch', models.PositiveIntegerField()),
                ('Mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advisor.teachers')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advisor.department')),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('urn', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('crn', models.PositiveIntegerField()),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('blood_group', models.CharField(max_length=4)),
                ('category', models.CharField(max_length=255)),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('living', models.CharField(choices=[('DAY SCHOLAR', 'DAY SCHOLAR'), ('HOSTELLER', 'HOSTELLER')], max_length=12)),
                ('Father_name', models.CharField(max_length=255)),
                ('Father_contact', models.PositiveIntegerField()),
                ('Mother_name', models.CharField(max_length=255)),
                ('Mother_contact', models.PositiveIntegerField()),
                ('Address', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=255)),
                ('District', models.CharField(max_length=255)),
                ('Pincode', models.PositiveIntegerField()),
                ('Contact', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advisor.Class')),
            ],
        ),
    ]
