# Generated by Django 2.2.5 on 2020-04-02 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Advisor', '0002_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Father_pic',
            field=models.ImageField(default=None, null=True, upload_to='father'),
        ),
        migrations.AddField(
            model_name='students',
            name='Mother_pic',
            field=models.ImageField(default=None, null=True, upload_to='mother'),
        ),
        migrations.AddField(
            model_name='students',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='students'),
        ),
    ]
