# Generated by Django 2.2.5 on 2020-04-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advisor', '0002_detailed_marks_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to='teachers'),
        ),
    ]
