# Generated by Django 2.2.5 on 2020-04-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advisor', '0003_teachers_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='picture',
        ),
        migrations.AddField(
            model_name='users',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to='teachers'),
        ),
    ]
