# Generated by Django 2.2.5 on 2020-04-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advisor', '0004_auto_20200412_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='picture',
            new_name='avatar',
        ),
    ]
