# Generated by Django 2.2.5 on 2020-04-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advisor', '0004_auto_20200402_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Father_pic',
            field=models.ImageField(default=None, null=True, upload_to='father'),
        ),
        migrations.AlterField(
            model_name='students',
            name='Mother_pic',
            field=models.ImageField(default=None, null=True, upload_to='mother'),
        ),
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='students'),
        ),
    ]
